### ISSUE TITLE
Documentation for features

### ISSUE THREAD

**Issue by 00sapo** [DIDONEproject/musif#41]
Add a page with feature documentation

**Comment by 00sapo** [comment]
I have added the table with the feature definition: https://musif.readthedocs.io/en/federico/Feature_definition.html

**Comment by 00sapo** [comment]
I have found various features that were not included by the regexs in our excel file as it is in Google Drive. I have fixed some of them in the documentation (not in the excel file!). @bichomartiano could this mean that our checks for errors are wrong?

See 2e6db2d0face5b7d1c782b3f69db00b95537574e for the version I'm referring to.

I have also created a script in `musiF_tests` that looks for features that are not matched by our regex (just run `python test_regexs.py` from my branch). The output is listed below. 

Overall, we need to document:
1.  all the features that have the description "TODO". From what I know, some of these features were designed by @egarpor, so he maybe can help us with one-line documentation of those features.
2. the features listed below

Then, we'll need to make sure that the `test_of_tests` script is using the same regex that are documented.

The latest version is still available at https://musif.readthedocs.io/en/federico/Feature_definition.html

```
PartBs_SmallestIntervalAll
SoundVa_SmallestIntervalDesc
PartBs_AscendingSemitones_Sum
SoundVa_IntervallicTrimRatio
SoundBs_SmallestIntervalAll
PartBs_SmallestIntervalDesc
PartVnI_AbsoluteIntervallicTrimRatio
PartSop_IntervallicTrimRatio
PartSop_LargestIntervalAll
SoundBs_AbsoluteIntervallicTrimRatio
PartVnI_LargestIntervalDesc
SoundVa_SmallestIntervalAsc
PartVa_AscendingSemitones_Sum
PartVa_IntervallicTrimRatio
Score_SmallestIntervalAll
PartVa_SmallestIntervalAll
SoundVa_AscendingSemitones_Sum
Score_AscendingSemitones_Sum
PartSop_LargestIntervalAsc
SoundBs_SmallestIntervalAsc
PartSop_SmallestIntervalAll
SoundVn_DescendingSemitones_Sum
PartVnII_IntervallicTrimRatio
PartSop_AscendingSemitones_Sum
PartSop_SmallestIntervalAsc
Score_AbsoluteIntervallicTrimRatio
PartVnII_LargestIntervalDesc
PartVa_DescendingSemitones_Sum
Score_SmallestIntervalAsc
PartSop_DescendingSemitones_Sum
PartVnI_DescendingSemitones_Sum
Score_LargestIntervalAsc
SoundSop_IntervallicTrimRatio
SoundVn_SmallestIntervalAsc
PartVnII_DescendingSemitones_Sum
SoundSop_SmallestIntervalAll
SoundSop_DescendingSemitones_Sum
SoundSop_AscendingSemitones_Sum
SoundBs_IntervallicTrimRatio
Score_LargestIntervalDesc
Score_DescendingSemitones_Sum
SoundVn_SmallestIntervalAll
PartVa_LargestIntervalAsc
PartVnII_LargestIntervalAll
SoundVn_LargestIntervalDesc
SoundVa_DescendingSemitones_Sum
SoundVn_AscendingSemitones_Sum
PartVa_SmallestIntervalAsc
SoundVn_LargestIntervalAll
PartVa_LargestIntervalDesc
SoundBs_LargestIntervalAll
PartVnI_LargestIntervalAsc
SoundSop_LargestIntervalDesc
SoundBs_SmallestIntervalDesc
SoundSop_LargestIntervalAll
SoundSop_AbsoluteIntervallicTrimRatio
PartVnII_AbsoluteIntervallicTrimRatio
SoundBs_LargestIntervalAsc
SoundVa_AbsoluteIntervallicTrimRatio
PartVnII_SmallestIntervalAll
PartVa_LargestIntervalAll
PartSop_SmallestIntervalDesc
PartVnI_IntervallicTrimRatio
PartVnI_SmallestIntervalAll
Score_SmallestIntervalDesc
PartSop_LargestIntervalDesc
PartVa_AbsoluteIntervallicTrimRatio
SoundVa_LargestIntervalAll
PartVnII_SmallestIntervalDesc
PartVnI_SmallestIntervalAsc
PartVnI_AscendingSemitones_Sum
PartBs_DescendingSemitones_Sum
PartBs_IntervallicTrimRatio
PartVnII_LargestIntervalAsc
SoundVn_IntervallicTrimRatio
PartVa_SmallestIntervalDesc
PartVnI_SmallestIntervalDesc
SoundVa_SmallestIntervalAll
PartVnII_AscendingSemitones_Sum
PartBs_SmallestIntervalAsc
PartSop_AbsoluteIntervallicTrimRatio
Score_IntervallicTrimRatio
PartVnII_SmallestIntervalAsc
SoundSop_SmallestIntervalDesc
SoundSop_LargestIntervalAsc
SoundBs_DescendingSemitones_Sum
SoundVn_LargestIntervalAsc
SoundVa_LargestIntervalDesc
PartBs_AbsoluteIntervallicTrimRatio
SoundVn_AbsoluteIntervallicTrimRatio
SoundSop_SmallestIntervalAsc
SoundVn_SmallestIntervalDesc
PartVnI_LargestIntervalAll
PartBs_LargestIntervalDesc
SoundBs_LargestIntervalDesc
PartBs_LargestIntervalAsc
PartBs_LargestIntervalAll
Score_LargestIntervalAll
SoundBs_AscendingSemitones_Sum
SoundVa_LargestIntervalAsc
Harmony_Analysis_Available
Harmony_Key_III_PercentageHarmony_Additions_+9
Harmony_Key_VI_PercentageHarmony_Additions_Others_no_+
Harmony_Key_i_PercentageHarmony_Additions_4_6_64
PartVnI_Dsc_prp
```

**Comment by 00sapo** [comment]
The regexs in the documentation of branch `federico` (`docs/source/Feature_definition.md`) are now complete. We should use these ones in the excel as well, but the order is not the same, so it's not just a simple copy-paste.

**Comment by 00sapo** [comment]
Closing this issue and leave https://github.com/DIDONEproject/musiF_tests/issues/1 open

**Comment by egarpor** [comment]
@00sapo, the features I designed were originally named as:

* `spe_avg_abs`: Absolute mean of the first-order quotients of the tick-indexed midi series.
* `acc_avg_abs`: Absolute mean of the second-order quotients of the tick-indexed midi series.
* `asc_avg`: Average length of ascent chunks of the midi series.
* `dsc_avg`: Average length of descent chunks of the midi series.
* `asc_prp`: Proportion of ascent chunks over the total of the midi series.
* `dsc_prp`: Proportion of descent chunks over the total of the midi series.

I think they correspond directly with

```
.+_Spe_avg_abs
.+_Acc_avg_abs
.+_Asc_avg
.+_Dsc_avg
.+_Asc_prp
.+_Dsc_prp
```

In any case, I think it is better to rename the first two features to

.+**_Foq**_avg_abs
.+**_Soq**_avg_abs

to remove the speed/acceleration connotations (which are more physical than musical).

**Comment by 00sapo** [comment]
Thak you Eduardo, I will re-ope this issue to track the TODO into the feature definition page

**Comment by 00sapo** [comment]
@egarpor what do you mean by "ascent chunks" and "descent chunks"? Also, I don't actually get the idea of "first-order quotients". Is it the first-order discrete derivative of the durations?

**Comment by egarpor** [comment]
* "ascent chunk" = "concatenation of non-decreasing midi values".
* Yes, "first-order quotient" equals "first-order discrete derivative". It can be changed to the latter if it is easier.

**Comment by 00sapo** [comment]
Thanks. Still don't understand which midi values: onsets?

**Comment by egarpor** [comment]
The ones codified as `Midind`: midi index.

**Comment by 00sapo** [comment]
From my understanding of the code, these are the definitions. However, I'm not sure the code is implemented correctly because the meaning of these features doesn't seem to be meaningful to me...

* `.+_Spe_avg_abs`: 1. represent each note as an array with N numbers having as value the note's MIDI pitch; here, N is the number of thirty-second notes that fill the whole note duration; 2. represent a melody part as the concatenation of such arrays; 3. take the discrete finite difference of the array for a specific part and divide by 0.125 (a thirty-second note duration); 4. this feature is the absolute mean of such an array
* `.+_Acc_avg_abs`: same as `.+_Spe_avg_abs` but uses second-order discrete finite difference (i.e. second-order discrete derivative)
* `.+_Asc_avg`: 1. given the array of a part used in `.+_Spe_avg_abs`, take a sliding window of size 9; 2. compute the average on each window, i.e. the average pitch in a window; 3. define a "chunk" as a sequence of windows having average pitch increasing or decreasing strictly and monotonically; this feature is the average number of windows in the ascending chunks
* `.+_Dsc_avg`: this is like `.+_Asc_avg` but for descending chunks
* `.+_Asc_prp`: number of ascending chunks over the total number of identified chunks (see `.+_Asc_avg`
* `.+_Dsc_prp`: number of descending chunks over the total number of identified chunks (see `.+_Asc_avg`

A short definition for `.+_Spe_avg_abs`: absolute mean of the first-order discrete derivative of the MIDI pitch sequence of a part, where the MIDI pitch is sampled with a resolution of 0.125 seconds. 

**Note that most of these first or second-order derivatives are 0 because melodies rarely change pitch in less than 0.25. Also note that all these feature strongly depend on the 0.125 and 9 parameters, while more of them should be inserted for a proper representation.**

**Comment by 00sapo** [comment]
Also, these features should not stay in the `rhythm` module, because all are related to the melody! I think they should stay in the `interval` module because they analyze how the difference between pitches change (the difference between pitches are intervals)

**Comment by egarpor** [comment]
Thanks for the very detailed comment.

> From my understanding of the code, these are the definitions. However, I'm not sure the code is implemented correctly because the meaning of some of these features doesn't seem to be meaningful to me (especially `.+_Spe_avg_abs` and `.+_Acc_avg_abs`)... @egarpor could you confirm this is what you meant?
> 
> * `.+_Spe_avg_abs`: 1. represent each note as an array with N numbers having as value the note's MIDI pitch; here, N is the number of thirty-second notes that fill the whole note duration; 2. represent a melody part as the concatenation of such arrays; 3. take the discrete finite difference of the array for a specific part and divide by 0.125 (a thirty-second note duration); 4. this feature is the absolute mean of such an array
> * `.+_Acc_avg_abs`: same as `.+_Spe_avg_abs` but uses second-order discrete finite difference (i.e. second-order discrete derivative)

Yes.

> * `.+_Asc_avg`: 1. given the array of a part used in `.+_Spe_avg_abs`, **take a sliding window of size 9**; 2. compute the average on each window, i.e. the average pitch in a window; 3. define a "chunk" as a sequence of windows having average pitch increasing or decreasing strictly and monotonically; this feature is the average number of windows in the ascending chunks
> * `.+_Dsc_avg`: this is like `.+_Asc_avg` but for descending chunks
> * `.+_Asc_prp`: number of ascending chunks over the total number of identified chunks (see `.+_Asc_avg`
> * `.+_Dsc_prp`: number of descending chunks over the total number of identified chunks (see `.+_Asc_avg`

The sliding window of size 9 was not in my original feature specification (in an R code before @bichomartiano translated to Python), which is simpler.

 `.+_Asc_avg` was meant to:

1. Given the array of a part used in `.+_Spe_avg_abs`, **look for all the increasing subsequences**. I.e., if the array is [1, 2, 3, 0, 1, -1, -3, 2], then the increasing subsequences are [1, 2, 3], [0, 1], [-3, 2]. Three subsequences of length 3, 2, 2. I called these subsequences as "ascending chunks".
2. Compute the average of all the lenghts of the found ascending subsequences.

> A short definition for `.+_Spe_avg_abs`: absolute mean of the first-order discrete derivative of the MIDI pitch sequence of a part, where the MIDI pitch is sampled with a resolution of 0.125 seconds. 

Yes. I had the understanding that 0.125 waa the minimal unit that made sense for our corpus. But better to state it.

> **Note that most of these first or second-order derivatives are 0 because melodies rarely change pitch in less than 0.25. Also note that all these feature strongly depend on the 0.125 and 9 parameters, while more of them should be inserted for a proper representation.**

Yes, the features depend on 0.125. A larger value will give a longer timespan and will give smoother outputs with less granularity.

**Comment by bichomartiano** [comment]
0.125 is not a seconds measure! It corres pongs to 1/8th of a quarter note (negra). So smaller values are allowed although very rare. I think @allorens can enlightn this a bit.

**Comment by allorens** [comment]
Yes, as Martin says, 0.125 is a demisemiquaver (or 32nd note = 1/8 of a quarter note). Smaller values could in principle exist, but they are definitely rare.

**Comment by 00sapo** [comment]
We still need to add these features. Moreover, they are now computed on several window and step sizes We should document this...

**Comment by martianbug** [comment]
Okay, so I adated the definitions  for these features and added it to the documentation. It looks like this right now:
![image](https://github.com/DIDONEproject/musif/assets/45066115/897bff22-05e9-40b8-92a2-859ad2400556)

If there is anything you'd like to change, just state it here and I'll change the definitions :)

**Comment by 00sapo** [comment]
Sorry Martín, some code changed and some things you have written are actually wrong. Could you use these definitions and feature names instead?

* `.+_Spe_avg_abs_step_.+_win_.+`: absolute mean of the first-order discrete derivative of the MIDI pitch sequence of a part, where the MIDI pitch is sampled with a given resolution (step); Step-size are defined in `musif.extract.features.melody.constants.MOTION_STEPS` 
* `.+_Acc_avg_abs_step_.+_win_.+`: same as `.+_Spe_avg_abs_step_.+_win_.+` but uses second-order discrete finite difference (i.e. second-order discrete derivative)
* `.+_Asc_avg_step_.+_win_.+`: 1. given the array of a part used in `.+_Spe_avg_abs_step_.+_win_.+`, take a sliding window of size `W`; 2. compute the average on each window, i.e. the average pitch in a window; 3. define a "chunk" as a sequence of windows having average pitch increasing or decreasing strictly and monotonically; this feature is the average number of windows in the ascending chunks. Window sized `W` are defined in `musif.extract.features.melody.constants.MOTION_WINS`.
* `.+_Dsc_avg_step_.+_win_.+`: this is like `.+_Asc_avg` but for descending chunks
* `.+_Asc_prp_step_.+_win_.+`: number of ascending chunks over the total number of identified chunks (see `.+_Asc_avg_step_.+_win_.+`)
* `.+_Dsc_prp_step_.+_win_.+`: number of descending chunks over the total number of identified chunks (see `.+_Asc_avg_step_.+_win_.+`)

**Comment by martianbug** [comment]
618d7b03c2e8d0fa039625aeb14e835d353f9d7f includes this documentation. I'll be released in the next version
