### ISSUE TITLE
Upgrade `ms3` to last version

### ISSUE THREAD

**Issue by 00sapo** [DIDONEproject/musif#43]

**Comment by bichomartiano** [comment]
What's up with this? Should we give it a try?

**Comment by 00sapo** [comment]
Just a lot of errors, but they should be easily solvable. Try it, if you like

**Comment by bichomartiano** [comment]
Hey, just got one error, solved by replacing .expanded attribute with the new .expanded() method. Already merged into develop.

**Comment by bichomartiano** [comment]
Yes
