### ISSUE TITLE
Convert "-" with "NA" in all the features

### ISSUE THREAD

**Issue by 00sapo** [DIDONEproject/musif#45]

**Comment by bichomartiano** [comment]
What about this_ Its supposed to be in the post processing or the extraction?

**Comment by 00sapo** [comment]
I think in the extraction, where there is the type casting and the NA -> pd.NA conversion. I think the output of the extraction should have homogeneous types before of the data processing

**Comment by bichomartiano** [comment]
Yes, I guess so. but i actually don't know what featueres come with a '-' in the data

**Comment by 00sapo** [comment]
Me neither, just check if there is any (there should) and replace them

**Comment by bichomartiano** [comment]
I checked and there is no '-' value in any column. I can put a replace just in case but theoretically there is no need

**Comment by 00sapo** [comment]
HAve checked with windows?

**Comment by bichomartiano** [comment]
Yep, I also checked
