### ISSUE TITLE
Difference between `.+_Intervals.+All_Count` and `.+_Interval.+_Count`

### ISSUE THREAD

**Issue by 00sapo** [DIDONEproject/musif#49]
I just don't get the difference from the name.

**Comment by bichomartiano** [comment]
Mm im not sure, i didn't define interval features. First one might be sum of all intervals and second the number of events of a certain type of interval (?)

**Comment by allorens** [comment]
The first one is the sume of the ascending and the descending intervals of the type, while the 2nd is the specific interval, including direction.
