### ISSUE TITLE
Duplicated parts expect a specific formating (1°, 2°) that is not standard in any way

### ISSUE THREAD

**Issue by 00sapo** [DIDONEproject/musif#51]
This commit introduce `prepare_parts`, that then became `_deal_with_duplicated_parts`, here is the lines I'm referring to in the code as it is now: https://github.com/DIDONEproject/musif/blob/15557aec1fd1f42ab6f4c73966bc9d96f29c5848/musif/extract/extract.py#L597-L603

I would remove it and add it to `musiF_tests`, as it looks very Didone specific.

**Comment by martianbug** [comment]
Hmm yes, it is very duidone specific. Actually only (and very) usefukl for corpora with repeating instruments

**Comment by 00sapo** [comment]
Fixed with https://github.com/DIDONEproject/musif/commit/6b7a5a6de61ae093d4ebec59caaf6d5eb209699a, moving this to musiF_tests
