### ISSUE TITLE
`xml_dir` should be `music21_dir`

### ISSUE THREAD

**Issue by 00sapo** [DIDONEproject/musif#52]
At now, the `xml_dir` is used to load files using music21. This is also stated in [docs](https://musif.didone.eu/File_loading.html). Using `music21_dir` would be more user-friendly. For instance, to load kern, MEI, midi, etc. the user can do: 

```python
musif.musicxml.constants.MUSIC21_FILE_EXTENSION = '.mid'
```

instead of 
```python
musif.musicxml.constants.MUSICXML_FILE_EXTENSION = '.mid'
```
It's rather strange saying that the extension of an XML file is `.mid`... this is highly misleading

**Comment by martianbug** [comment]
True. I just agree

**Comment by 00sapo** [comment]
Right now, this is implemented, but it's not documented. Also, we need to expose these variables in the configuration files (this and MUSESCORE_FILE_EXTENSION).
