### ISSUE TITLE
Incorrect link to manually download data

### ISSUE THREAD

**Issue by johentsch** [DIDONEproject/musif#58]
Currently, the "download [this](https://zenodo.org/record/4027957) dataset" on the site https://musif.didone.eu/Tutorial%20poprock.html#data is pointing to the "Composer Attribution of Renaissance Motets" on Zenodo, not to the pop-rock scores correctly referenced in the following code cell: https://figshare.com/ndownloader/articles/5436031/versions/1

**Comment by martianbug** [comment]
Ficed! Thanks
