### ISSUE TITLE
Documentation of `update_part_objects`  and `update_score_objects`

### ISSUE THREAD

**Issue by CarlosVaquero** [DIDONEproject/musif#61]
For a new joiner, it is not clear what the relation between these two methods is. Let's try to make it more clear in a dummy handler.py or in the documentation itself.

**Comment by CarlosVaquero** [comment]
Moved to Musif

**Comment by 00sapo** [comment]
Which part of the documentation did you find not effective? https://musif.didone.eu/Custom_features.html

**Comment by martianbug** [comment]
I think he means in the code itself, to createnew features whats the difference between both methods.
I will just clarify itmore in the Tutorial_poprock, where a custom feature is created

**Comment by martianbug** [comment]
82945aaf236d2b4ecfc1b7c18280380571b168a4 fixes this
