### ISSUE TITLE
Error in music21-jsymbolic overlap

### ISSUE THREAD

**Issue by 00sapo** [DIDONEproject/musif#63]
https://github.com/DIDONEproject/musif/blob/2e9808428345db94738b5b370fa887e398580d5d/musif/extract/features/music21/handler.py#L49

This should just be `not in`

**Comment by 00sapo** [comment]
Also, just later, this line is not working:

https://github.com/DIDONEproject/musif/blob/main/musif/extract/features/music21/handler.py#LL54C23-L54C63

It should be like:
```python
all_columns = [x.id for x in extractorsById("all", library="native")]
```

**Comment by 00sapo** [comment]
Moreover, it would be better to have the ids of the features out of our `allFeaturesAsList()` to avoid possible mismatching. Not least, it would be better to use the class name instead of the id of each feature: 

`allFeaturesAsList()` should return something like `all_data, [c.__class__.__name__ for c in all_features]`

**Comment by martianbug** [comment]
Ok, issues 1 and 2 are fixed. About the 3:
I've changed the funcion so i returns as you metioned but that information is not used later? 
About the ERROR_NAMES, i ran all the features withthe cache activated and none of them threw an error

**Comment by 00sapo** [comment]
It is not used now, it should replace the `all_columns` variable defined in this part of code:
https://github.com/DIDONEproject/musif/blob/2e9808428345db94738b5b370fa887e398580d5d/musif/extract/features/music21/handler.py#L51-L54

This is why `ERROR_NAMES` should be updated: it now contains the `id` attribute of each music21 features, but now we are planning to use the class' name string, which is more explicative

**Comment by 00sapo** [comment]
About `ERROR_NAMES`, please double-check that all the features work even on the second run. If they work, we can use all of them, otherwise, we need to put the features that break the cache in that variable.

**Comment by martianbug** [comment]
OK, done!
