### ISSUE TITLE
File loading

### ISSUE THREAD

**Issue by 00sapo** [DIDONEproject/musif#67]
The file-loading system right now creates a lot of headaches. We need to simplify it. My proposal (braking change!):

1. I would rename xml_dir to music21_dir in the configuration files as well
2. I would expose MUSESCORE_FILE_EXTENSION and MUSIC21_FILE_EXTENSIONS in the config file
3. I would add a third option that is harmony_dir  which will still contain musescore files but intended for the harmony analysis, so no Musescore installation needed for that directory
4. I would say in the docs that music21_dir have precedence over musescore_dir always (so if both are provided, musescore_dir is simply disregarded). harmony_dir is instead used only if provided and via ms3 , not MuseScore
5. I would add a check of the version of musescore and say that we need Musescore 3 because Musescore 4 has a bug

**Comment by 00sapo** [comment]
After discussing, we decided that the user can:

1. use both `data_dir` and `musescore_dir`
2. use `data_dir` and not `musescore_dir` and a warning is printed
3. if no `data_dir` is provided, an exception is thrown and the program stops

Everything inside `data_dir` is loaded with music21.
Everything inside `musescore_dir` is loaded with ms3.

Files are looked for recursively using respectively `MUSIC21_FILE_EXTENSIONS` and `MUSESCORE_FILE_EXTENSIONS` which are lists of extensions (any file having one of these extensions is loaded).

**Comment by martianbug** [comment]
0938dcefa64bca32a8e58f351933fbd17cf60568 and cd47661db09ec356644ce22d00c4b4342397bb70should fix all of this.
