### ISSUE TITLE
Mixed types in 'Act' column

### ISSUE THREAD

**Issue by CarlosVaquero** [DIDONEproject/musif#70]
![image](https://github.com/DIDONEproject/musif/assets/1258125/0ba54f72-7e7f-49ec-92a1-9c937e48b8dc)

**Comment by martianbug** [comment]
Buenas,

No he podido replicar este erorr coon los datos de la última extracción (07_08). No había ningun valor de Act que igualase 1 o 2 como números int, aunque sí al buscar equivalencias con '1' o '2'.
![image](https://github.com/DIDONEproject/musif/assets/45066115/33147783-3b54-4c30-bd77-ac31c38faec3)

Lo que sí he encontrado es Act  == 'X' y UNA aria con valor 'x'. La corregiré. Pero creo que estos casos son de aquellas que no se conoce en qué acto era, o no se ha averiguado aún. Para más info consulta a @allorens .

![image](https://github.com/DIDONEproject/musif/assets/45066115/34d3613d-2e4d-4063-8cc1-e52a98f267be)

Saludos!
