### ISSUE TITLE
Python <3.10 Support

### ISSUE THREAD

**Issue by JLenzy** [DIDONEproject/musif#72]
Hi there,
First - thanks for making such a great tool. You all rock!
Second - is there any plan for supporting python versions below 3.10? Many pipelines and tools are designed around python 3.7-3.9. I have a current project in which I'd love to use Musif but will likely have to use alternatives because the existing code base requires 3.8.

Thanks a lot!

**Comment by martianbug** [comment]
Hi! First of all, thank for using our dear tool! its great to hear from users getting the most out of music :)
Send of all, sorry for the tremendous delay! Next time try to assign the issue to some member of Didone Organization of we might just miss the thing :)
And, about the issue,  right now we aren't developing further features of music therefore extending its support to previous versions of python doesn't seem likely. It's require some recoding of the source code and at this moment we are not in a position to do so. Le me know if you managed to include it in your code or if you could find a workaround, and how is your current situation.
Thanks in advance and again sorry for the delay!
